--liquibase formatted sql

--changeset punko_vitaliy:4

DROP SEQUENCE IF EXISTS BANK.BANK_ACCOUNTS_SEQ;

drop table if exists BANK.BANK_ACCOUNTS;

create table IF NOT EXISTS BANK.BANK_ACCOUNTS
(
    ID
    INTEGER
    PRIMARY
    KEY,
    BANK_ACCOUNT_NUMBER
    VARCHAR
(
    50
),
    BALANCE NUMERIC
(
    19,
    4
),
    OPEN_DATE TIMESTAMP,
    CLOSE_DATE TIMESTAMP,
    CLIENT_ID INTEGER REFERENCES BANK.CLIENTS
(
    ID
)
    );

ALTER TABLE BANK.BANK_ACCOUNTS
    ADD CONSTRAINT UNIQUE_BANK_ACCOUNT_NUMBER
        UNIQUE (BANK_ACCOUNT_NUMBER);

CREATE SEQUENCE IF NOT EXISTS BANK.BANK_ACCOUNTS_SEQ;